In [1]:
#Clone the git repo

!git clone https://github.com/PhonePe/pulse.git

fatal: destination path 'pulse' already exists and is not an empty directory.

In [2]:
import os
import json
import pandas as pd

In [3]:
# Folder path for Transaction data
transaction_path = r"C:\Users\Varshini V\OneDrive\Documents\VS_code\pulse\data\aggregated\transaction\country\india\state/"

states = os.listdir(transaction_path) # extracts the states from the transaction path and stores in the states parameter aas list
transaction_list = []

for state in states:
    state_path = transaction_path + state + "/" # extractes the path including the state names
    years = os.listdir(state_path) # creates the list of years of each state
    
    for year in years:
        year_path = state_path + year + "/" #extractes the list of years from the years parameter and converts to path
        quarters = os.listdir(year_path) #creates the list of quarters for each year

        for quarter in quarters:
            file_path = year_path + quarter
            with open(file_path) as f:
                data = json.load(f)

             # Extract data safely
            if data["data"]["transactionData"] is not None:
                for item in data["data"]["transactionData"]:
                    for instrument in item["paymentInstruments"]:
                        transaction_list.append({
                            "State": state,
                            "Year": year,
                            "Quarter": quarter.strip(".json"),
                            "Transaction_Name": item["name"],
                            "Transaction_Count": instrument["count"],
                            "Transaction_Amount": instrument["amount"]
                        })

# Convert to DataFrame
df_transaction = pd.DataFrame(transaction_list)
df_transaction

,State,Year,Quarter,Transaction_Name,Transaction_Count,Transaction_Amount
0,andaman-&-nicobar-islands,2018,1,Recharge & bill payments,4200,1.845307e+06
1,andaman-&-nicobar-islands,2018,1,Peer-to-peer payments,1871,1.213866e+07
2,andaman-&-nicobar-islands,2018,1,Merchant payments,298,4.525072e+05
3,andaman-&-nicobar-islands,2018,1,Financial Services,33,1.060142e+04
4,andaman-&-nicobar-islands,2018,1,Others,256,1.846899e+05
...,...,...,...,...,...,...
5029,west-bengal,2024,4,Merchant payments,655100809,3.892862e+11
5030,west-bengal,2024,4,Peer-to-peer payments,493217788,1.361927e+12
5031,west-bengal,2024,4,Recharge & bill payments,76043195,5.753406e+10
5032,west-bengal,2024,4,Financial Services,2352084,8.472965e+08
5033,west-bengal,2024,4,Others,421806,5.053641e+08

In [4]:
transaction_path_map = r"C:\Users\Varshini V\OneDrive\Documents\VS_code\venv\program\pulse\data\map\transaction\hover\country\india\state/"

states = os.listdir(transaction_path_map)
user_list2 = []

for state in states:
    state_path = os.path.join(transaction_path_map, state)
    years = os.listdir(state_path)

    for year in years:
        year_path = os.path.join(state_path, year)
        quarters = os.listdir(year_path)

        for quarter in quarters:
            file_path = os.path.join(year_path, quarter)
            with open(file_path) as f:
                data = json.load(f)

            if data.get("data") and "hoverDataList" in data["data"]:
                for item in data["data"]["hoverDataList"]:
                        for item2 in item["metric"]:
                            user_list2.append({
                            "State": state,
                            "Year": year,
                            "Quarter": quarter.strip(".json"),
                            "District": item["name"],
                            "Transaction_Count": item2["count"],
                            "Transaction_Amount": item2["amount"]
                            })

# Convert to DataFrame
df_transaction_map = pd.DataFrame(user_list2)
print(df_transaction_map)

                           State  Year Quarter  \
0      andaman-&-nicobar-islands  2018       1
1      andaman-&-nicobar-islands  2018       1
2      andaman-&-nicobar-islands  2018       1
3      andaman-&-nicobar-islands  2018       2
4      andaman-&-nicobar-islands  2018       2
...                          ...   ...     ...
20599                west-bengal  2024       4
20600                west-bengal  2024       4
20601                west-bengal  2024       4
20602                west-bengal  2024       4
20603                west-bengal  2024       4

                                District  Transaction_Count  \
0      north and middle andaman district                442
1                 south andaman district               5688
2                      nicobars district                528
3      north and middle andaman district                825
4                 south andaman district               9395
...                                  ...                ...
20599                alipurduar district           15875637
20600         paschim bardhaman district           56616799
20601                     nadia district           65274337
20602                   birbhum district           36905213
20603           purba medinipur district           67833775

       Transaction_Amount
0            9.316631e+05
1            1.256025e+07
2            1.139849e+06
3            1.317863e+06
4            2.394824e+07
...                   ...
20599        2.099251e+10
20600        6.968735e+10
20601        1.079320e+11
20602        5.778701e+10
20603        1.142771e+11

[20604 rows x 6 columns]

In [5]:
transaction_top = r"C:\Users\Varshini V\OneDrive\Documents\VS_code\venv\program\pulse\data\top\transaction\country\india\state/"

states = os.listdir(transaction_top)
user_list2 = []

for state in states:
    state_path = os.path.join(transaction_top, state)
    years = os.listdir(state_path)

    for year in years:
        year_path = os.path.join(state_path, year)
        quarters = os.listdir(year_path)

        for quarter in quarters:
            file_path = os.path.join(year_path, quarter)
            with open(file_path) as f:
                data = json.load(f)

            if data["data"]["districts"] and data["data"]["pincodes"] is not None:
                for item in data["data"]["districts"]:
                    for item2 in data["data"]["pincodes"]:
                           user_list2.append({
                            "State": state,
                            "Year": year,
                            "Quarter": quarter.strip(".json"),
                            "District": item['entityName'],
                            "Transaction_Count": item['metric']['count'],
                            "Transaction_Amount": item['metric']['amount'],
                            "Pincodes": item2['entityName'],
                            "Pin_trans_count": item2['metric']["count"],
                            "Pin_trans_amount": item2["metric"]["amount"]
                            })
# Convert to DataFrame
df_transaction_top = pd.DataFrame(user_list2)
print(df_transaction_top)

                           State  Year Quarter           District  \
0      andaman-&-nicobar-islands  2018       1      south andaman
1      andaman-&-nicobar-islands  2018       1      south andaman
2      andaman-&-nicobar-islands  2018       1      south andaman
3      andaman-&-nicobar-islands  2018       1      south andaman
4      andaman-&-nicobar-islands  2018       1      south andaman
...                          ...   ...     ...                ...
82822                west-bengal  2024       4  paschim medinipur
82823                west-bengal  2024       4  paschim medinipur
82824                west-bengal  2024       4  paschim medinipur
82825                west-bengal  2024       4  paschim medinipur
82826                west-bengal  2024       4  paschim medinipur

       Transaction_Count  Transaction_Amount Pincodes  Pin_trans_count  \
0                   5688        1.256025e+07   744101             1622
1                   5688        1.256025e+07   744103             1223
2                   5688        1.256025e+07   744102              969
3                   5688        1.256025e+07   744105              685
4                   5688        1.256025e+07   744104              340
...                  ...                 ...      ...              ...
82822           58238212        8.431774e+10   711101          6753348
82823           58238212        8.431774e+10   700059          6662715
82824           58238212        8.431774e+10   700039          6575693
82825           58238212        8.431774e+10   734001          6432082
82826           58238212        8.431774e+10   733134          6313560

       Pin_trans_amount
0          2.769298e+06
1          2.238042e+06
2          3.519060e+06
3          1.298561e+06
4          1.039715e+06
...                 ...
82822      1.049483e+10
82823      8.009476e+09
82824      9.018748e+09
82825      8.996529e+09
82826      1.050259e+10

[82827 rows x 9 columns]

In [6]:
# Folder path for User data
insurance_path = r"C:\Users\Varshini V\OneDrive\Documents\VS_code\venv\program\pulse\data\aggregated\insurance\country\india\state/"

states = os.listdir(insurance_path)
insurance_list = []

for state in states:
    state_path = insurance_path + state + "/"
    years = os.listdir(state_path)

    for year in years:
        year_path = state_path + year + "/"
        quarters = os.listdir(year_path)

        for quarter in quarters:
            file_path = year_path + quarter
            with open(file_path) as f:
                data = json.load(f)

            if data["data"]["transactionData"] is not None:
                for item in data["data"]["transactionData"]:
                    for instrument in item["paymentInstruments"]:
                      insurance_list.append({
                        "State": state,
                        "Year": year,
                        "Quarter": quarter.strip(".json"),
                        "Insurance_Count": instrument["count"],
                        "Insurance_Amount": instrument["amount"]
                    })

# Convert to DataFrame
df_insurance = pd.DataFrame(insurance_list)
df_insurance

,State,Year,Quarter,Insurance_Count,Insurance_Amount
0,andaman-&-nicobar-islands,2020,2,6,1360.0
1,andaman-&-nicobar-islands,2020,3,41,15380.0
2,andaman-&-nicobar-islands,2020,4,124,157975.0
3,andaman-&-nicobar-islands,2021,1,225,244266.0
4,andaman-&-nicobar-islands,2021,2,137,181504.0
...,...,...,...,...,...
677,west-bengal,2023,4,72712,100365562.0
678,west-bengal,2024,1,79576,104987909.0
679,west-bengal,2024,2,67048,89476633.0
680,west-bengal,2024,3,77158,107451766.0
681,west-bengal,2024,4,91719,120602777.0

In [7]:
insurance_map = r"C:\Users\Varshini V\OneDrive\Documents\VS_code\venv\program\pulse\data\map\insurance\hover\country\india\state/"

states = os.listdir(insurance_map)
user_list2 = []

for state in states:
    state_path = os.path.join(insurance_map, state)
    years = os.listdir(state_path)

    for year in years:
        year_path = os.path.join(state_path, year)
        quarters = os.listdir(year_path)

        for quarter in quarters:
            file_path = os.path.join(year_path, quarter)
            with open(file_path) as f:
                data = json.load(f)

            if data.get("data") and "hoverDataList" in data["data"]:
                for item in data["data"]["hoverDataList"]:
                    for item2 in item["metric"]:
                           user_list2.append({
                            "State": state,
                            "Year": year,
                            "Quarter": quarter.strip(".json"),
                            "District": item["name"],
                            "Count": item2["count"],
                            "Amount": item2["amount"]
                            })

# Convert to DataFrame
df_insurance_map = pd.DataFrame(user_list2)
print(df_insurance_map)

                           State  Year Quarter  \
0      andaman-&-nicobar-islands  2020       2
1      andaman-&-nicobar-islands  2020       2
2      andaman-&-nicobar-islands  2020       3
3      andaman-&-nicobar-islands  2020       3
4      andaman-&-nicobar-islands  2020       3
...                          ...   ...     ...
13871                west-bengal  2024       4
13872                west-bengal  2024       4
13873                west-bengal  2024       4
13874                west-bengal  2024       4
13875                west-bengal  2024       4

                                District  Count     Amount
0                 south andaman district      3      795.0
1                      nicobars district      3      565.0
2      north and middle andaman district      1      281.0
3                 south andaman district     35    13651.0
4                      nicobars district      5     1448.0
...                                  ...    ...        ...
13871                alipurduar district   1023  1613143.0
13872         paschim bardhaman district   4945  7005851.0
13873                     nadia district   3807  5031294.0
13874                   birbhum district   1818  2423290.0
13875           purba medinipur district   3559  4439061.0

[13876 rows x 6 columns]

In [8]:
insurance_top = r"C:\Users\Varshini V\OneDrive\Documents\VS_code\venv\program\pulse\data\top\insurance\country\india\state/"

states = os.listdir(insurance_top)
user_list2 = []

for state in states:
    state_path = os.path.join(insurance_top, state)
    years = os.listdir(state_path)

    for year in years:
        year_path = os.path.join(state_path, year)
        quarters = os.listdir(year_path)

        for quarter in quarters:
            file_path = os.path.join(year_path, quarter)
            with open(file_path) as f:
                data = json.load(f)

            if data["data"]["districts"] and data["data"]["pincodes"] is not None:
                for item in data["data"]["districts"]:
                    for item2 in data["data"]["pincodes"]:
                           user_list2.append({
                            "State": state,
                            "Year": year,
                            "Quarter": quarter.strip(".json"),
                            "District": item['entityName'],
                            "Transaction_Count": item['metric']['count'],
                            "Transaction_Amount": item['metric']['amount'],
                            "Pincodes": item2['entityName'],
                            "Pin_trans_count": item2['metric']["count"],
                            "Pin_trans_amount": item2["metric"]["amount"]
                            })
# Convert to DataFrame
df_insurance_top = pd.DataFrame(user_list2)
print(df_insurance_top)

                           State  Year Quarter         District  \
0      andaman-&-nicobar-islands  2020       2         nicobars
1      andaman-&-nicobar-islands  2020       2         nicobars
2      andaman-&-nicobar-islands  2020       2         nicobars
3      andaman-&-nicobar-islands  2020       2    south andaman
4      andaman-&-nicobar-islands  2020       2    south andaman
...                          ...   ...     ...              ...
55828                west-bengal  2024       4  purba bardhaman
55829                west-bengal  2024       4  purba bardhaman
55830                west-bengal  2024       4  purba bardhaman
55831                west-bengal  2024       4  purba bardhaman
55832                west-bengal  2024       4  purba bardhaman

       Transaction_Count  Transaction_Amount Pincodes  Pin_trans_count  \
0                      3               565.0   744301                3
1                      3               565.0   744104                2
2                      3               565.0   744101                1
3                      3               795.0   744301                3
4                      3               795.0   744104                2
...                  ...                 ...      ...              ...
55828               3595           4482879.0   711101              713
55829               3595           4482879.0   700091              642
55830               3595           4482879.0   700150              627
55831               3595           4482879.0   700039              619
55832               3595           4482879.0   700156              574

       Pin_trans_amount
0                 565.0
1                 513.0
2                 282.0
3                 565.0
4                 513.0
...                 ...
55828          750354.0
55829          969634.0
55830          761501.0
55831          787836.0
55832          888613.0

[55833 rows x 9 columns]

In [12]:
# Folder path for User data
user_path = r"C:\Users\Varshini V\OneDrive\Documents\VS_code\venv\program\pulse\data\aggregated\user\country\india\state/"

states = os.listdir(user_path)
user_list = []

for state in states:
    state_path = user_path + state + "/"
    years = os.listdir(state_path)

    for year in years:
        year_path = state_path + year + "/"
        quarters = os.listdir(year_path)

        for quarter in quarters:
            file_path = year_path + quarter
            with open(file_path) as f:
                data = json.load(f)

            if data["data"]["usersByDevice"] is not None:
                for item in data["data"]["usersByDevice"]:
                    user_list.append({
                        "State": state,
                        "Year": year,
                        "Quarter": quarter.strip(".json"),
                        "Device_Brand": item["brand"],
                        "Device_Count": item["count"],
                        "Device_Percentage": item["percentage"]
                    })

# Convert to DataFrame
df_user = pd.DataFrame(user_list)
df_user

,State,Year,Quarter,Device_Brand,Device_Count,Device_Percentage
0,andaman-&-nicobar-islands,2018,1,Xiaomi,1665,0.247033
1,andaman-&-nicobar-islands,2018,1,Samsung,1445,0.214392
2,andaman-&-nicobar-islands,2018,1,Vivo,982,0.145697
3,andaman-&-nicobar-islands,2018,1,Oppo,501,0.074332
4,andaman-&-nicobar-islands,2018,1,OnePlus,332,0.049258
...,...,...,...,...,...,...
6727,west-bengal,2022,1,Lenovo,330017,0.015056
6728,west-bengal,2022,1,Infinix,284678,0.012987
6729,west-bengal,2022,1,Asus,280347,0.012790
6730,west-bengal,2022,1,Apple,277752,0.012671
6731,west-bengal,2022,1,Others,2196334,0.100199

In [10]:
# Folder path for User data
user_map = r"C:\Users\Varshini V\OneDrive\Documents\VS_code\venv\program\pulse\data\map\user\hover\country\india\state/"

states = os.listdir(user_map)
user_list2 = []

for state in states:
    state_path = os.path.join(user_map, state)
    years = os.listdir(state_path)

    for year in years:
        year_path = os.path.join(state_path, year)
        quarters = os.listdir(year_path)

        for quarter in quarters:
            file_path = os.path.join(year_path, quarter)
            with open(file_path) as f:
                data = json.load(f)

            if data.get("data") and "hoverData" in data["data"]:
                for district, values in data["data"]["hoverData"].items():
                    user_list2.append({
                        "State": state,
                        "Year": year,
                        "Quarter": quarter.strip(".json"),
                        "District": district,
                        "Registered_users": values.get("registeredUsers"),
                        "App_opens": values.get("appOpens")
                    })

# Convert to DataFrame
df_user_map = pd.DataFrame(user_list2)
print(df_user_map)

                           State  Year Quarter  \
0      andaman-&-nicobar-islands  2018       1
1      andaman-&-nicobar-islands  2018       1
2      andaman-&-nicobar-islands  2018       1
3      andaman-&-nicobar-islands  2018       2
4      andaman-&-nicobar-islands  2018       2
...                          ...   ...     ...
20603                west-bengal  2024       4
20604                west-bengal  2024       4
20605                west-bengal  2024       4
20606                west-bengal  2024       4
20607                west-bengal  2024       4

                                District  Registered_users  App_opens
0      north and middle andaman district               632          0
1                 south andaman district              5846          0
2                      nicobars district               262          0
3      north and middle andaman district               911          0
4                 south andaman district              8143          0
...                                  ...               ...        ...
20603                alipurduar district            475688   31842355
20604         paschim bardhaman district           1468252   80543469
20605                     nadia district           1861738   98740305
20606                   birbhum district           1114220   73465525
20607           purba medinipur district           1717074  108350777

[20608 rows x 6 columns]

In [11]:
# Folder path for User data
user_path_top = r"C:\Users\Varshini V\OneDrive\Documents\VS_code\venv\program\pulse\data\top\user\country\india\state/"

states = os.listdir(user_path_top)
user_list3 = []

for state in states:
    state_path = os.path.join(user_path_top, state)
    years = os.listdir(state_path)

    for year in years:
        year_path = os.path.join(state_path, year)
        quarters = os.listdir(year_path)

        for quarter in quarters:
            file_path = os.path.join(year_path, quarter)
            with open(file_path) as f:
                data = json.load(f)

            if data["data"]["districts"] and data["data"]["pincodes"] is not None:
                for item in data["data"]["districts"]:
                    for item2 in data["data"]["pincodes"]:
                           user_list3.append({
                            "State": state,
                            "Year": year,
                            "Quarter": quarter.strip(".json"),
                            "District": item['name'],
                            "Registered_users": item['registeredUsers'],
                            "Pincodes": item2['name'],
                            "Pin_registered_users": item2["registeredUsers"]
                    })

# Convert to DataFrame
df_user_top = pd.DataFrame(user_list3)
print(df_user_top)

                           State  Year Quarter           District  \
0      andaman-&-nicobar-islands  2018       1      south andaman
1      andaman-&-nicobar-islands  2018       1      south andaman
2      andaman-&-nicobar-islands  2018       1      south andaman
3      andaman-&-nicobar-islands  2018       1      south andaman
4      andaman-&-nicobar-islands  2018       1      south andaman
...                          ...   ...     ...                ...
82823                west-bengal  2024       4  paschim bardhaman
82824                west-bengal  2024       4  paschim bardhaman
82825                west-bengal  2024       4  paschim bardhaman
82826                west-bengal  2024       4  paschim bardhaman
82827                west-bengal  2024       4  paschim bardhaman

       Registered_users Pincodes  Pin_registered_users
0                  5846   744103                  1608
1                  5846   744101                  1108
2                  5846   744105                  1075
3                  5846   744102                  1006
4                  5846   744104                   272
...                 ...      ...                   ...
82823           1468252   733134                169596
82824           1468252   700059                169448
82825           1468252   711302                146034
82826           1468252   700150                142151
82827           1468252   711106                142077

[82828 rows x 7 columns]

In [13]:
pip install sqlalchemy

Requirement already satisfied: sqlalchemy in c:\users\varshini v\onedrive\documents\vs_code\venv\lib\site-packages (2.0.44)
Requirement already satisfied: greenlet>=1 in c:\users\varshini v\onedrive\documents\vs_code\venv\lib\site-packages (from sqlalchemy) (3.3.0)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\varshini v\onedrive\documents\vs_code\venv\lib\site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [14]:
pip install pymysql

Requirement already satisfied: pymysql in c:\users\varshini v\onedrive\documents\vs_code\venv\lib\site-packages (1.1.2)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [15]:
from sqlalchemy import create_engine
engine = create_engine("mysql+pymysql://root:tiger=123@127.0.0.1:3306/phonepe")

#engine = create_engine("mysql+pymysql://{username}:{password}@{host}:{port}/{database}")

conn = engine.connect()
print("Connection successful!")

Connection successful!

In [16]:
# write the dataframes to Mysql workbench using the sqlalchemy
df_transaction.to_sql("transaction_data", con=engine, if_exists="replace", index=False)
df_transaction_map.to_sql("transaction_path_map", con=engine, if_exists="replace", index=False)
df_transaction_top.to_sql("transaction_top",con=engine,if_exists="replace", index= False)
df_insurance.to_sql("insurance_data", con=engine, if_exists="replace", index=False)
df_insurance_map.to_sql("insurance_map",con=engine,if_exists="replace", index=False)
df_insurance_top.to_sql("insurance_top", con=engine, if_exists="replace", index= False)
df_user.to_sql("user_data", con=engine, if_exists="replace", index=False)
df_user_map.to_sql("user_data_map", con=engine, if_exists="replace", index=False)
df_user_top.to_sql("user_data_top", con=engine, if_exists="replace", index=False)

82828